In [1]:
from sklearn import datasets
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB,GaussianNB
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import numpy as np

In [19]:
data=datasets.fetch_20newsgroups()

In [20]:
len(data.data)

11314

# Preprossing

In [23]:
x=data.data
y=data.target

In [25]:
data.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [18]:
pd.DataFrame(x).head(1)

                                                   0
0  From: lerxst@wam.umd.edu (where's my thing)\nS...

In [5]:
pd.DataFrame(y).head()

    0
0   7
1   4
2   4
3   1
4  14

In [6]:
clf=TfidfVectorizer()
p=clf.fit_transform(data.data)

In [7]:
x_train,x_test,y_train,y_test=train_test_split(data.data,data.target)
x1_train=clf.fit_transform(x_train)
x1_test=clf.transform(x_test)

In [8]:
clf1=MultinomialNB()
clf1.fit(x1_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [21]:
y_pred=clf1.predict(x1_test)

In [27]:
y_pred[:100]

array([ 5,  8,  1, 14,  7,  3,  5,  5,  4,  9, 14,  0,  3,  8,  7, 14, 13,
       15, 16, 14,  5, 15, 17,  4, 15, 15, 11, 17, 16, 13,  2, 15, 15,  2,
       15, 16, 16, 10, 12, 16, 16, 11, 13,  7,  8, 15, 13, 12, 15, 16, 11,
       15,  9,  8, 14, 15, 11, 16, 12, 10, 15,  0, 18, 13, 15, 15,  4, 11,
        3, 14,  3, 10,  3,  3, 11, 13,  1,  9,  3,  9,  0, 11, 10,  5, 10,
       15,  4, 15, 13, 12, 11,  9, 18, 18,  7, 11, 15,  7, 11,  0])

In [10]:
clf1.score(x1_train,y_train),clf1.score(x1_test,y_test)

(0.9319976428992339, 0.8289148108872393)

In [11]:
pd.DataFrame(confusion_matrix(y_test,y_pred))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,82,0,0,0,0,0,0,0,0,0,0,1,0,0,0,19,0,0,0,0
1,0,107,1,7,2,2,0,0,0,0,0,4,1,1,0,5,1,0,1,0
2,0,4,119,16,1,3,1,2,0,1,0,5,0,0,0,5,1,0,0,0
3,0,3,2,120,6,1,1,3,1,0,0,2,1,0,1,3,0,0,0,0
4,0,0,2,9,116,0,1,1,1,0,0,9,1,0,0,1,0,0,0,0
5,0,5,2,6,1,119,0,2,1,1,0,12,0,0,1,2,0,0,0,0
6,0,1,1,11,1,0,99,10,3,3,0,5,5,0,3,4,3,0,0,0
7,0,0,0,0,0,0,0,126,5,1,0,1,3,0,1,3,2,0,0,0
8,0,0,0,1,0,0,0,2,141,0,0,1,0,0,0,2,2,0,0,0
9,0,0,0,0,0,0,1,0,0,137,6,1,0,0,1,4,0,0,0,0
10,0,0,0,2,0,0,0,0,0,1,150,1,0,0,0,1,0,0,0,0
11,0,3,0,0,0,0,0,0,0,0,0,148,0,0,0,1,0,0,0,0
12,1,0,0,7,5,0,1,6,0,0,0,9,110,0,2,5,0,1,0,0
13,0,0,0,1,0,0,0,0,0,0,0,4,0,134,2,4,0,1,0,0
14,0,1,0,0,1,0,1,0,0,0,0,2,0,0,154,5,0,0,0,0
15,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,140,0,0,0,0
16,1,0,0,0,0,0,0,0,0,0,0,3,0,0,0,2,133,0,0,0
17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,132,0,0
18,0,0,0,0,0,0,0,0,0,1,0,8,0,1,2,26,14,4,70,0
19,13,0,0,0,0,0,0,2,0,1,0,0,0,1,0,65,12,3,0,8

In [12]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.80      0.82       102
           1       0.86      0.81      0.84       132
           2       0.94      0.75      0.84       158
           3       0.67      0.83      0.74       144
           4       0.87      0.82      0.84       141
           5       0.95      0.78      0.86       152
           6       0.94      0.66      0.78       149
           7       0.82      0.89      0.85       142
           8       0.93      0.95      0.94       149
           9       0.94      0.91      0.93       150
          10       0.96      0.97      0.96       155
          11       0.69      0.97      0.80       152
          12       0.91      0.75      0.82       147
          13       0.98      0.92      0.95       146
          14       0.92      0.94      0.93       164
          15       0.47      0.99      0.63       141
          16       0.79      0.96      0.87       139
          17       0.94      0.98      0.96       135
          18       0.99      0.56      0.71       126
          19       1.00      0.08      0.14       105

   micro avg       0.83      0.83      0.83      2829
   macro avg       0.87      0.82      0.81      2829
weighted avg       0.87      0.83      0.82      2829

In [13]:
model = make_pipeline(TfidfVectorizer(), MultinomialNB())

In [14]:
model.fit(x_train,y_train)

Pipeline(memory=None,
     steps=[('tfidfvectorizer', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth...   vocabulary=None)), ('multinomialnb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [15]:
pred=model.predict(x_test)

In [16]:
model.score(x_test,y_test)

0.8289148108872393

In [17]:
accuracy_score(y_test,y_pred)

0.8289148108872393